In [1]:
import numpy as np
import pandas as pd

c:\Users\Nalipi Sridhar Reddy\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [6]:
date = pd.read_csv('DataSets\DataSet\messages.csv')

time = pd.read_csv('DataSets\DataSet\orders.csv')

In [7]:
date.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
time.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [11]:
# Converting 'date' column to datetime type
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [12]:
# Extracting year from the date
date['date_year'] = date['date'].dt.year
date.sample(5)

,date,msg,date_year
538,2014-02-06 23:45:00,Ищю мужа и отца для моего ребёнка. Мне 20л. Зв...,2014
117,2014-10-21 00:48:00,*** по телефону перезвоню сама.Анна,2014
83,2014-02-07 23:14:00,Хочу заявить на весь днепр что у меня самый лу...,2014
602,2015-01-08 00:38:00,Познакомлюсь с девушкой 050 992 99 08,2015
138,2015-07-30 23:40:00,М.- с Ж. Пошепчемся? - 099 735 08 03,2015

In [13]:
# Extracting month (number)
date['date_month_no'] = date['date'].dt.month
date.head()

,date,msg,date_year,date_month_no
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10

In [14]:
# Extracting month (name)
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,msg,date_year,date_month_no,date_month_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October

In [15]:
# Extracting day
date['date_day'] = date['date'].dt.day
date.head()

,date,msg,date_year,date_month_no,date_month_name,date_day
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December,15
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April,29
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December,30
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November,28
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October,26

In [16]:
# Day of week (as number)
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,msg,date_year,date_month_no,date_month_name,date_day,date_dow
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December,15,6
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April,29,1
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December,30,6
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November,28,4
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October,26,5

In [17]:
# Day of week (as name)
date['date_dow_name'] = date['date'].dt.day_name()
columns_to_drop = ['product_id', 'city_id', 'orders']
existing_cols = [col for col in columns_to_drop if col in date.columns]
date.drop(columns=existing_cols).head()

,date,msg,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December,15,6,Sunday
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April,29,1,Tuesday
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December,30,6,Sunday
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November,28,4,Friday
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October,26,5,Saturday

In [18]:
# Is weekend?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)
columns_to_drop = ['product_id', 'city_id', 'orders']
existing_cols = [col for col in columns_to_drop if col in date.columns]
date.drop(columns=existing_cols).head()

,date,msg,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December,15,6,Sunday,1
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April,29,1,Tuesday,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December,30,6,Sunday,1
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November,28,4,Friday,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October,26,5,Saturday,1